#!/usr/bin/env python3
"""
Score transaction_mart rows with trained numpy logistic model.
Writes scores to SQLite table: fraud_scores
"""

from __future__ import annotations

import argparse
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


def stable_sigmoid(x: np.ndarray) -> np.ndarray:
    out = np.empty_like(x, dtype=np.float64)
    pos = x >= 0
    neg = ~pos
    out[pos] = 1.0 / (1.0 + np.exp(-x[pos]))
    exp_x = np.exp(x[neg])
    out[neg] = exp_x / (1.0 + exp_x)
    return out


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Score transaction_mart with trained fraud baseline.")
    parser.add_argument("--db-path", default="data/warehouse/ledger_sentinel.db", help="SQLite DB path")
    parser.add_argument(
        "--model-path",
        required=True,
        help="Path to model.npz generated by train_fraud_baseline_numpy.py",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        default=["ieee_cis", "creditcard_fraud", "paysim"],
        help="Datasets to score",
    )
    parser.add_argument("--max-rows", type=int, default=None, help="Optional max rows to score")
    parser.add_argument(
        "--max-rows-per-dataset",
        type=int,
        default=None,
        help="Optional per-dataset row cap (recommended for balanced smoke runs)",
    )
    parser.add_argument("--chunksize", type=int, default=100000, help="SQL read chunksize")
    parser.add_argument(
        "--output-root",
        default="artifacts/models/fraud_scoring",
        help="Output root for scoring summary",
    )
    return parser.parse_args()


def parse_categorical_features(feature_names: List[str], numeric_names: List[str]) -> Dict[str, List[str]]:
    cat_map: Dict[str, List[str]] = {
        "dataset_id": [],
        "channel": [],
        "txn_type": [],
        "currency": [],
    }
    for feat in feature_names:
        if feat in numeric_names:
            continue
        for key in cat_map.keys():
            prefix = f"{key}_"
            if feat.startswith(prefix):
                cat_map[key].append(feat[len(prefix) :])
                break
    return cat_map


def build_matrix(
    df: pd.DataFrame,
    feature_names: List[str],
    numeric_names: List[str],
    numeric_means: np.ndarray,
    numeric_stds: np.ndarray,
) -> np.ndarray:
    frame = df.copy()
    frame["amount"] = pd.to_numeric(frame["amount"], errors="coerce").fillna(0.0)
    frame["payer_txn_count_24h"] = pd.to_numeric(frame["payer_txn_count_24h"], errors="coerce").fillna(0.0)
    frame["payer_amt_sum_24h"] = pd.to_numeric(frame["payer_amt_sum_24h"], errors="coerce").fillna(0.0)
    frame["graph_payer_incoming_txn_count_24h"] = (
        pd.to_numeric(frame["graph_payer_incoming_txn_count_24h"], errors="coerce").fillna(0.0)
    )
    frame["graph_payer_unique_payees_24h"] = (
        pd.to_numeric(frame["graph_payer_unique_payees_24h"], errors="coerce").fillna(0.0)
    )
    frame["graph_pair_txn_count_30d"] = pd.to_numeric(frame["graph_pair_txn_count_30d"], errors="coerce").fillna(0.0)
    frame["graph_pair_amt_sum_30d"] = pd.to_numeric(frame["graph_pair_amt_sum_30d"], errors="coerce").fillna(0.0)
    frame["graph_reciprocal_pair_txn_count_30d"] = (
        pd.to_numeric(frame["graph_reciprocal_pair_txn_count_30d"], errors="coerce").fillna(0.0)
    )
    frame["event_time"] = pd.to_datetime(frame["event_time"], errors="coerce")
    frame["hour_of_day"] = frame["event_time"].dt.hour.fillna(0).astype(np.float64)
    frame["day_of_week"] = frame["event_time"].dt.dayofweek.fillna(0).astype(np.float64)
    frame["log_amount"] = np.log1p(frame["amount"].clip(lower=0))
    frame["log_payer_amt_sum_24h"] = np.log1p(frame["payer_amt_sum_24h"].clip(lower=0))
    frame["log_graph_pair_amt_sum_30d"] = np.log1p(frame["graph_pair_amt_sum_30d"].clip(lower=0))

    num_base = pd.DataFrame(
        {
            "log_amount": frame["log_amount"],
            "payer_txn_count_24h": frame["payer_txn_count_24h"],
            "log_payer_amt_sum_24h": frame["log_payer_amt_sum_24h"],
            "graph_payer_incoming_txn_count_24h": frame["graph_payer_incoming_txn_count_24h"],
            "graph_payer_unique_payees_24h": frame["graph_payer_unique_payees_24h"],
            "graph_pair_txn_count_30d": frame["graph_pair_txn_count_30d"],
            "log_graph_pair_amt_sum_30d": frame["log_graph_pair_amt_sum_30d"],
            "graph_reciprocal_pair_txn_count_30d": frame["graph_reciprocal_pair_txn_count_30d"],
            "hour_of_day": frame["hour_of_day"],
            "day_of_week": frame["day_of_week"],
        }
    )
    num_x = num_base[numeric_names].to_numpy(dtype=np.float64)
    num_x = (num_x - numeric_means) / numeric_stds
    num_x = np.nan_to_num(num_x, nan=0.0, posinf=0.0, neginf=0.0)

    cat_map = parse_categorical_features(feature_names, numeric_names)
    cat_cols: List[np.ndarray] = []
    for feat in feature_names:
        if feat in numeric_names:
            continue
        matched = False
        for key, values in cat_map.items():
            prefix = f"{key}_"
            if feat.startswith(prefix):
                val = feat[len(prefix) :]
                s = frame[key].fillna("UNK").astype(str)
                cat_cols.append((s == val).astype(np.float64).to_numpy())
                matched = True
                break
        if not matched:
            cat_cols.append(np.zeros(len(frame), dtype=np.float64))

    cat_x = np.column_stack(cat_cols) if cat_cols else np.zeros((len(frame), 0), dtype=np.float64)
    x = np.hstack([num_x, cat_x])
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)
    return x


def main() -> None:
    args = parse_args()
    db_path = Path(args.db_path)
    model_path = Path(args.model_path)
    if not db_path.exists():
        raise FileNotFoundError(f"Missing DB: {db_path}")
    if not model_path.exists():
        raise FileNotFoundError(f"Missing model file: {model_path}")

    model = np.load(model_path, allow_pickle=True)
    w = model["weights"].astype(np.float64)
    b = float(model["bias"][0])
    feature_names = [str(x) for x in model["feature_names"].tolist()]
    numeric_names = [str(x) for x in model["numeric_feature_names"].tolist()]
    numeric_means = model["numeric_means"].astype(np.float64)
    numeric_stds = model["numeric_stds"].astype(np.float64)

    global_query = f"""
    SELECT
      tm.event_id,
      tm.dataset_id,
      tm.event_time,
      tm.channel,
      tm.txn_type,
      tm.currency,
      tm.amount,
      tm.label_fraud,
      COALESCE(f.payer_txn_count_24h, 0.0) AS payer_txn_count_24h,
      COALESCE(f.payer_amt_sum_24h, 0.0) AS payer_amt_sum_24h,
      COALESCE(g.graph_payer_incoming_txn_count_24h, 0.0) AS graph_payer_incoming_txn_count_24h,
      COALESCE(g.graph_payer_unique_payees_24h, 0.0) AS graph_payer_unique_payees_24h,
      COALESCE(g.graph_pair_txn_count_30d, 0.0) AS graph_pair_txn_count_30d,
      COALESCE(g.graph_pair_amt_sum_30d, 0.0) AS graph_pair_amt_sum_30d,
      COALESCE(g.graph_reciprocal_pair_txn_count_30d, 0.0) AS graph_reciprocal_pair_txn_count_30d
    FROM transaction_mart tm
    LEFT JOIN feature_payer_24h f
      ON f.event_id = tm.event_id
    LEFT JOIN feature_graph_24h g
      ON g.event_id = tm.event_id
    WHERE tm.dataset_id IN ({{placeholders}})
    ORDER BY tm.event_time
    {{max_clause}}
    """

    read_conn = sqlite3.connect(db_path)
    write_conn = sqlite3.connect(db_path)
    read_conn.execute("PRAGMA journal_mode = WAL;")
    write_conn.execute("PRAGMA journal_mode = WAL;")
    read_conn.execute("PRAGMA busy_timeout = 60000;")
    write_conn.execute("PRAGMA busy_timeout = 60000;")

    # Drop previous scores once before streaming writes.
    write_conn.execute("DROP TABLE IF EXISTS fraud_scores;")
    write_conn.commit()

    total_rows = 0
    dataset_rows: Dict[str, int] = {}

    def consume_chunk(chunk: pd.DataFrame) -> None:
        nonlocal total_rows
        x = build_matrix(chunk, feature_names, numeric_names, numeric_means, numeric_stds)
        with np.errstate(over="ignore", divide="ignore", invalid="ignore"):
            logits = x @ w + b
        logits = np.nan_to_num(logits, nan=0.0, posinf=50.0, neginf=-50.0)
        scores = stable_sigmoid(logits)

        out = pd.DataFrame(
            {
                "event_id": chunk["event_id"].astype(str),
                "dataset_id": chunk["dataset_id"].astype(str),
                "event_time": chunk["event_time"].astype(str),
                "fraud_score": scores.astype(np.float64),
                "label_fraud": pd.to_numeric(chunk["label_fraud"], errors="coerce"),
            }
        )
        out.to_sql("fraud_scores", write_conn, if_exists="append", index=False, chunksize=1000)
        write_conn.commit()
        total_rows += len(out)
        for ds, cnt in out["dataset_id"].value_counts().items():
            dataset_rows[ds] = dataset_rows.get(ds, 0) + int(cnt)
        print(f"[SCORE] rows={total_rows}", flush=True)

    if args.max_rows_per_dataset is not None:
        per_limit = int(args.max_rows_per_dataset)
        query_per_ds = """
        SELECT
          tm.event_id,
          tm.dataset_id,
          tm.event_time,
          tm.channel,
          tm.txn_type,
          tm.currency,
          tm.amount,
          tm.label_fraud,
          COALESCE(f.payer_txn_count_24h, 0.0) AS payer_txn_count_24h,
          COALESCE(f.payer_amt_sum_24h, 0.0) AS payer_amt_sum_24h,
          COALESCE(g.graph_payer_incoming_txn_count_24h, 0.0) AS graph_payer_incoming_txn_count_24h,
          COALESCE(g.graph_payer_unique_payees_24h, 0.0) AS graph_payer_unique_payees_24h,
          COALESCE(g.graph_pair_txn_count_30d, 0.0) AS graph_pair_txn_count_30d,
          COALESCE(g.graph_pair_amt_sum_30d, 0.0) AS graph_pair_amt_sum_30d,
          COALESCE(g.graph_reciprocal_pair_txn_count_30d, 0.0) AS graph_reciprocal_pair_txn_count_30d
        FROM transaction_mart tm
        LEFT JOIN feature_payer_24h f
          ON f.event_id = tm.event_id
        LEFT JOIN feature_graph_24h g
          ON g.event_id = tm.event_id
        WHERE tm.dataset_id = ?
        ORDER BY tm.event_time
        LIMIT ?
        """
        for ds in args.datasets:
            for chunk in pd.read_sql_query(query_per_ds, read_conn, params=[ds, per_limit], chunksize=args.chunksize):
                consume_chunk(chunk)
    else:
        placeholders = ",".join(["?"] * len(args.datasets))
        max_clause = f"LIMIT {int(args.max_rows)}" if args.max_rows else ""
        query = global_query.format(placeholders=placeholders, max_clause=max_clause)
        for chunk in pd.read_sql_query(query, read_conn, params=args.datasets, chunksize=args.chunksize):
            consume_chunk(chunk)

    cur = write_conn.cursor()
    cur.executescript(
        """
        CREATE INDEX IF NOT EXISTS idx_fs_event_id ON fraud_scores(event_id);
        CREATE INDEX IF NOT EXISTS idx_fs_dataset_time ON fraud_scores(dataset_id, event_time);
        """
    )
    write_conn.commit()

    summary = {
        "created_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "db_path": str(db_path),
        "model_path": str(model_path),
        "datasets": args.datasets,
        "total_scored_rows": total_rows,
        "rows_by_dataset": dataset_rows,
    }

    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_dir = Path(args.output_root) / run_id
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "scoring-summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    read_conn.close()
    write_conn.close()
    print(f"[DONE] scoring summary: {out_dir / 'scoring-summary.json'}", flush=True)


if __name__ == "__main__":
    main()
